setwd("/Users/shuqingchen/Library/CloudStorage/Box-Box/Neighbors")
#install.packages("predictrace")
library(predictrace)
library(haven)
library(dplyr)
library(purrr)
library(rethnicity)
rm(list=ls())
FL_names <- read.csv("~/Library/CloudStorage/Box-Box/Neighbors/Datasets/Intermediate/FL_names.csv")
FL_names <- FL_names %>% distinct(fname,lname)
predicted_races<-predict_ethnicity(firstnames = FL_names$fname, lastnames = FL_names$lname, method = "fullname", threads = parallel::detectCores()-2)
predicted_races <- predicted_races%>% select(c("firstname","lastname","race")) %>% rename(fname=firstname,lname=lastname)
write_dta(predicted_races, "/Users/shuqingchen/Library/CloudStorage/Box-Box/Neighbors/Datasets/Intermediate/Predicted_race_FL.dta")